/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = MyDataMyConsent.Client.OpenAPIDateConverter;

namespace MyDataMyConsent.Models
{
    /// <summary>
    /// DataConsentDocumentsDto
    /// </summary>
    [DataContract(Name = "DataConsentDocumentsDto")]
    public partial class DataConsentDocumentsDto : IEquatable<DataConsentDocumentsDto>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataConsentDocumentsDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="documents">documents.</param>
        /// <param name="approvedDocuments">approvedDocuments.</param>
        public DataConsentDocumentsDto(Guid id = default(Guid), List<Document> documents = default(List<Document>), List<DataConsentRequestedDocument> approvedDocuments = default(List<DataConsentRequestedDocument>))
        {
            this.Id = id;
            this.Documents = documents;
            this.ApprovedDocuments = approvedDocuments;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Documents
        /// </summary>
        [DataMember(Name = "documents", EmitDefaultValue = true)]
        public List<Document> Documents { get; set; }

        /// <summary>
        /// Gets or Sets ApprovedDocuments
        /// </summary>
        [DataMember(Name = "approvedDocuments", EmitDefaultValue = true)]
        public List<DataConsentRequestedDocument> ApprovedDocuments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataConsentDocumentsDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("  ApprovedDocuments: ").Append(ApprovedDocuments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataConsentDocumentsDto);
        }

        /// <summary>
        /// Returns true if DataConsentDocumentsDto instances are equal
        /// </summary>
        /// <param name="input">Instance of DataConsentDocumentsDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataConsentDocumentsDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Documents == input.Documents ||
                    this.Documents != null &&
                    input.Documents != null &&
                    this.Documents.SequenceEqual(input.Documents)
                ) && 
                (
                    this.ApprovedDocuments == input.ApprovedDocuments ||
                    this.ApprovedDocuments != null &&
                    input.ApprovedDocuments != null &&
                    this.ApprovedDocuments.SequenceEqual(input.ApprovedDocuments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Documents != null)
                {
                    hashCode = (hashCode * 59) + this.Documents.GetHashCode();
                }
                if (this.ApprovedDocuments != null)
                {
                    hashCode = (hashCode * 59) + this.ApprovedDocuments.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
