/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = MyDataMyConsent.Client.OpenAPIDateConverter;

namespace MyDataMyConsent.Models
{
    /// <summary>
    /// Rejection
    /// </summary>
    [DataContract(Name = "Rejection")]
    public partial class Rejection : IEquatable<Rejection>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rejection" /> class.
        /// </summary>
        /// <param name="reason">reason.</param>
        /// <param name="rejectedBy">rejectedBy.</param>
        /// <param name="rejectedAtUtc">rejectedAtUtc.</param>
        public Rejection(string reason = default(string), Guid rejectedBy = default(Guid), DateTime rejectedAtUtc = default(DateTime))
        {
            this.Reason = reason;
            this.RejectedBy = rejectedBy;
            this.RejectedAtUtc = rejectedAtUtc;
        }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets RejectedBy
        /// </summary>
        [DataMember(Name = "rejectedBy", EmitDefaultValue = false)]
        public Guid RejectedBy { get; set; }

        /// <summary>
        /// Gets or Sets RejectedAtUtc
        /// </summary>
        [DataMember(Name = "rejectedAtUtc", EmitDefaultValue = false)]
        public DateTime RejectedAtUtc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rejection {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  RejectedBy: ").Append(RejectedBy).Append("\n");
            sb.Append("  RejectedAtUtc: ").Append(RejectedAtUtc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Rejection);
        }

        /// <summary>
        /// Returns true if Rejection instances are equal
        /// </summary>
        /// <param name="input">Instance of Rejection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Rejection input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                ) && 
                (
                    this.RejectedBy == input.RejectedBy ||
                    (this.RejectedBy != null &&
                    this.RejectedBy.Equals(input.RejectedBy))
                ) && 
                (
                    this.RejectedAtUtc == input.RejectedAtUtc ||
                    (this.RejectedAtUtc != null &&
                    this.RejectedAtUtc.Equals(input.RejectedAtUtc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Reason != null)
                {
                    hashCode = (hashCode * 59) + this.Reason.GetHashCode();
                }
                if (this.RejectedBy != null)
                {
                    hashCode = (hashCode * 59) + this.RejectedBy.GetHashCode();
                }
                if (this.RejectedAtUtc != null)
                {
                    hashCode = (hashCode * 59) + this.RejectedAtUtc.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
