/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = MyDataMyConsent.Client.OpenAPIDateConverter;

namespace MyDataMyConsent.Models
{
    /// <summary>
    /// UserDocumentDownloadDto
    /// </summary>
    [DataContract(Name = "UserDocumentDownloadDto")]
    public partial class UserDocumentDownloadDto : IEquatable<UserDocumentDownloadDto>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserDocumentDownloadDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="storageUrl">storageUrl.</param>
        /// <param name="ownerId">ownerId.</param>
        public UserDocumentDownloadDto(Guid id = default(Guid), string storageUrl = default(string), Guid ownerId = default(Guid))
        {
            this.Id = id;
            this.StorageUrl = storageUrl;
            this.OwnerId = ownerId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets StorageUrl
        /// </summary>
        [DataMember(Name = "storageUrl", EmitDefaultValue = true)]
        public string StorageUrl { get; set; }

        /// <summary>
        /// Gets or Sets OwnerId
        /// </summary>
        [DataMember(Name = "ownerId", EmitDefaultValue = false)]
        public Guid OwnerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserDocumentDownloadDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StorageUrl: ").Append(StorageUrl).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserDocumentDownloadDto);
        }

        /// <summary>
        /// Returns true if UserDocumentDownloadDto instances are equal
        /// </summary>
        /// <param name="input">Instance of UserDocumentDownloadDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserDocumentDownloadDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.StorageUrl == input.StorageUrl ||
                    (this.StorageUrl != null &&
                    this.StorageUrl.Equals(input.StorageUrl))
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.StorageUrl != null)
                {
                    hashCode = (hashCode * 59) + this.StorageUrl.GetHashCode();
                }
                if (this.OwnerId != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerId.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
