/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Sdk.Api;
using MyDataMyConsent.Sdk.Models;
using MyDataMyConsent.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DataConsentDetailsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataConsentDetailsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataConsentDetailsDto
        //private DataConsentDetailsDto instance;

        public DataConsentDetailsDtoTests()
        {
            // TODO uncomment below to create an instance of DataConsentDetailsDto
            //instance = new DataConsentDetailsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataConsentDetailsDto
        /// </summary>
        [Fact]
        public void DataConsentDetailsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataConsentDetailsDto
            //Assert.IsType<DataConsentDetailsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ApprovedAtUtc'
        /// </summary>
        [Fact]
        public void ApprovedAtUtcTest()
        {
            // TODO unit test for the property 'ApprovedAtUtc'
        }
        /// <summary>
        /// Test the property 'RejectedAtUtc'
        /// </summary>
        [Fact]
        public void RejectedAtUtcTest()
        {
            // TODO unit test for the property 'RejectedAtUtc'
        }
        /// <summary>
        /// Test the property 'ExpiresAtUtc'
        /// </summary>
        [Fact]
        public void ExpiresAtUtcTest()
        {
            // TODO unit test for the property 'ExpiresAtUtc'
        }
        /// <summary>
        /// Test the property 'RequestedAtUtc'
        /// </summary>
        [Fact]
        public void RequestedAtUtcTest()
        {
            // TODO unit test for the property 'RequestedAtUtc'
        }
        /// <summary>
        /// Test the property 'Requester'
        /// </summary>
        [Fact]
        public void RequesterTest()
        {
            // TODO unit test for the property 'Requester'
        }
        /// <summary>
        /// Test the property 'ConsentDetails'
        /// </summary>
        [Fact]
        public void ConsentDetailsTest()
        {
            // TODO unit test for the property 'ConsentDetails'
        }
        /// <summary>
        /// Test the property 'Identifiers'
        /// </summary>
        [Fact]
        public void IdentifiersTest()
        {
            // TODO unit test for the property 'Identifiers'
        }
        /// <summary>
        /// Test the property 'ApprovedDocuments'
        /// </summary>
        [Fact]
        public void ApprovedDocumentsTest()
        {
            // TODO unit test for the property 'ApprovedDocuments'
        }
        /// <summary>
        /// Test the property 'ApprovedFinancials'
        /// </summary>
        [Fact]
        public void ApprovedFinancialsTest()
        {
            // TODO unit test for the property 'ApprovedFinancials'
        }

    }

}
