/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Sdk.Api;
using MyDataMyConsent.Sdk.Models;
using MyDataMyConsent.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentIssueRequestDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentIssueRequestDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentIssueRequestDetails
        //private DocumentIssueRequestDetails instance;

        public DocumentIssueRequestDetailsTests()
        {
            // TODO uncomment below to create an instance of DocumentIssueRequestDetails
            //instance = new DocumentIssueRequestDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentIssueRequestDetails
        /// </summary>
        [Fact]
        public void DocumentIssueRequestDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentIssueRequestDetails
            //Assert.IsType<DocumentIssueRequestDetails>(instance);
        }


        /// <summary>
        /// Test the property 'DocumentTypeId'
        /// </summary>
        [Fact]
        public void DocumentTypeIdTest()
        {
            // TODO unit test for the property 'DocumentTypeId'
        }
        /// <summary>
        /// Test the property 'DocumentTypeName'
        /// </summary>
        [Fact]
        public void DocumentTypeNameTest()
        {
            // TODO unit test for the property 'DocumentTypeName'
        }
        /// <summary>
        /// Test the property 'DocumentIdentifier'
        /// </summary>
        [Fact]
        public void DocumentIdentifierTest()
        {
            // TODO unit test for the property 'DocumentIdentifier'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Receiver'
        /// </summary>
        [Fact]
        public void ReceiverTest()
        {
            // TODO unit test for the property 'Receiver'
        }
        /// <summary>
        /// Test the property 'ExpiresAtUtc'
        /// </summary>
        [Fact]
        public void ExpiresAtUtcTest()
        {
            // TODO unit test for the property 'ExpiresAtUtc'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'CreatedAtUtc'
        /// </summary>
        [Fact]
        public void CreatedAtUtcTest()
        {
            // TODO unit test for the property 'CreatedAtUtc'
        }

    }

}
