/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Sdk.Api;
using MyDataMyConsent.Sdk.Models;
using MyDataMyConsent.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing FinancialAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FinancialAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FinancialAccount
        //private FinancialAccount instance;

        public FinancialAccountTests()
        {
            // TODO uncomment below to create an instance of FinancialAccount
            //instance = new FinancialAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FinancialAccount
        /// </summary>
        [Fact]
        public void FinancialAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" FinancialAccount
            //Assert.IsType<FinancialAccount>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Fact]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'AccountLogoUrl'
        /// </summary>
        [Fact]
        public void AccountLogoUrlTest()
        {
            // TODO unit test for the property 'AccountLogoUrl'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'BalanceType'
        /// </summary>
        [Fact]
        public void BalanceTypeTest()
        {
            // TODO unit test for the property 'BalanceType'
        }
        /// <summary>
        /// Test the property 'IsShared'
        /// </summary>
        [Fact]
        public void IsSharedTest()
        {
            // TODO unit test for the property 'IsShared'
        }
        /// <summary>
        /// Test the property 'SharedWith'
        /// </summary>
        [Fact]
        public void SharedWithTest()
        {
            // TODO unit test for the property 'SharedWith'
        }
        /// <summary>
        /// Test the property 'IsReceived'
        /// </summary>
        [Fact]
        public void IsReceivedTest()
        {
            // TODO unit test for the property 'IsReceived'
        }
        /// <summary>
        /// Test the property 'ExpiresAtUtc'
        /// </summary>
        [Fact]
        public void ExpiresAtUtcTest()
        {
            // TODO unit test for the property 'ExpiresAtUtc'
        }
        /// <summary>
        /// Test the property 'Activities'
        /// </summary>
        [Fact]
        public void ActivitiesTest()
        {
            // TODO unit test for the property 'Activities'
        }
        /// <summary>
        /// Test the property 'ApprovedConsentRequests'
        /// </summary>
        [Fact]
        public void ApprovedConsentRequestsTest()
        {
            // TODO unit test for the property 'ApprovedConsentRequests'
        }

    }

}
