/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Sdk.Api;
using MyDataMyConsent.Sdk.Models;
using MyDataMyConsent.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetConsentTemplateDetailsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetConsentTemplateDetailsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetConsentTemplateDetailsDto
        //private GetConsentTemplateDetailsDto instance;

        public GetConsentTemplateDetailsDtoTests()
        {
            // TODO uncomment below to create an instance of GetConsentTemplateDetailsDto
            //instance = new GetConsentTemplateDetailsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetConsentTemplateDetailsDto
        /// </summary>
        [Fact]
        public void GetConsentTemplateDetailsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetConsentTemplateDetailsDto
            //Assert.IsType<GetConsentTemplateDetailsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ConsentPurpose'
        /// </summary>
        [Fact]
        public void ConsentPurposeTest()
        {
            // TODO unit test for the property 'ConsentPurpose'
        }
        /// <summary>
        /// Test the property 'Collectables'
        /// </summary>
        [Fact]
        public void CollectablesTest()
        {
            // TODO unit test for the property 'Collectables'
        }
        /// <summary>
        /// Test the property 'FetchType'
        /// </summary>
        [Fact]
        public void FetchTypeTest()
        {
            // TODO unit test for the property 'FetchType'
        }
        /// <summary>
        /// Test the property 'ShortId'
        /// </summary>
        [Fact]
        public void ShortIdTest()
        {
            // TODO unit test for the property 'ShortId'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedAtUtc'
        /// </summary>
        [Fact]
        public void CreatedAtUtcTest()
        {
            // TODO unit test for the property 'CreatedAtUtc'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TemplateType'
        /// </summary>
        [Fact]
        public void TemplateTypeTest()
        {
            // TODO unit test for the property 'TemplateType'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Identity'
        /// </summary>
        [Fact]
        public void IdentityTest()
        {
            // TODO unit test for the property 'Identity'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'Financials'
        /// </summary>
        [Fact]
        public void FinancialsTest()
        {
            // TODO unit test for the property 'Financials'
        }

    }

}
