/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Sdk.Api;
using MyDataMyConsent.Sdk.Models;
using MyDataMyConsent.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Receiver
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReceiverTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Receiver
        //private Receiver instance;

        public ReceiverTests()
        {
            // TODO uncomment below to create an instance of Receiver
            //instance = new Receiver();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Receiver
        /// </summary>
        [Fact]
        public void ReceiverInstanceTest()
        {
            // TODO uncomment below to test "IsType" Receiver
            //Assert.IsType<Receiver>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Identifiers'
        /// </summary>
        [Fact]
        public void IdentifiersTest()
        {
            // TODO unit test for the property 'Identifiers'
        }
        /// <summary>
        /// Test the property 'IdentificationStrategy'
        /// </summary>
        [Fact]
        public void IdentificationStrategyTest()
        {
            // TODO unit test for the property 'IdentificationStrategy'
        }

    }

}
