/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Sdk.Api;
using MyDataMyConsent.Sdk.Models;
using MyDataMyConsent.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SupportedIdentifiersByCountry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupportedIdentifiersByCountryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupportedIdentifiersByCountry
        //private SupportedIdentifiersByCountry instance;

        public SupportedIdentifiersByCountryTests()
        {
            // TODO uncomment below to create an instance of SupportedIdentifiersByCountry
            //instance = new SupportedIdentifiersByCountry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupportedIdentifiersByCountry
        /// </summary>
        [Fact]
        public void SupportedIdentifiersByCountryInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupportedIdentifiersByCountry
            //Assert.IsType<SupportedIdentifiersByCountry>(instance);
        }


        /// <summary>
        /// Test the property 'Iso2'
        /// </summary>
        [Fact]
        public void Iso2Test()
        {
            // TODO unit test for the property 'Iso2'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Flag'
        /// </summary>
        [Fact]
        public void FlagTest()
        {
            // TODO unit test for the property 'Flag'
        }
        /// <summary>
        /// Test the property 'IndividualIdentifiers'
        /// </summary>
        [Fact]
        public void IndividualIdentifiersTest()
        {
            // TODO unit test for the property 'IndividualIdentifiers'
        }
        /// <summary>
        /// Test the property 'OrganizationIdentifiers'
        /// </summary>
        [Fact]
        public void OrganizationIdentifiersTest()
        {
            // TODO unit test for the property 'OrganizationIdentifiers'
        }

    }

}
