/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Api;
using MyDataMyConsent.Models;
using MyDataMyConsent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentDetails
        //private ConsentDetails instance;

        public ConsentDetailsTests()
        {
            // TODO uncomment below to create an instance of ConsentDetails
            //instance = new ConsentDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentDetails
        /// </summary>
        [Fact]
        public void ConsentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentDetails
            //Assert.IsType<ConsentDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Fact]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'ApprovedAtUtc'
        /// </summary>
        [Fact]
        public void ApprovedAtUtcTest()
        {
            // TODO unit test for the property 'ApprovedAtUtc'
        }
        /// <summary>
        /// Test the property 'DataAccessExpiresAtUtc'
        /// </summary>
        [Fact]
        public void DataAccessExpiresAtUtcTest()
        {
            // TODO unit test for the property 'DataAccessExpiresAtUtc'
        }
        /// <summary>
        /// Test the property 'RevokedAtUtc'
        /// </summary>
        [Fact]
        public void RevokedAtUtcTest()
        {
            // TODO unit test for the property 'RevokedAtUtc'
        }
        /// <summary>
        /// Test the property 'Collectables'
        /// </summary>
        [Fact]
        public void CollectablesTest()
        {
            // TODO unit test for the property 'Collectables'
        }
        /// <summary>
        /// Test the property 'Identifiers'
        /// </summary>
        [Fact]
        public void IdentifiersTest()
        {
            // TODO unit test for the property 'Identifiers'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'MedicalRecords'
        /// </summary>
        [Fact]
        public void MedicalRecordsTest()
        {
            // TODO unit test for the property 'MedicalRecords'
        }
        /// <summary>
        /// Test the property 'FinancialAccounts'
        /// </summary>
        [Fact]
        public void FinancialAccountsTest()
        {
            // TODO unit test for the property 'FinancialAccounts'
        }

    }

}
