/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Api;
using MyDataMyConsent.Models;
using MyDataMyConsent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Test.Model
{
    /// <summary>
    ///  Class for testing CreditCardTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditCardTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditCardTransaction
        //private CreditCardTransaction instance;

        public CreditCardTransactionTests()
        {
            // TODO uncomment below to create an instance of CreditCardTransaction
            //instance = new CreditCardTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditCardTransaction
        /// </summary>
        [Fact]
        public void CreditCardTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditCardTransaction
            //Assert.IsType<CreditCardTransaction>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TxnType'
        /// </summary>
        [Fact]
        public void TxnTypeTest()
        {
            // TODO unit test for the property 'TxnType'
        }
        /// <summary>
        /// Test the property 'TxnDate'
        /// </summary>
        [Fact]
        public void TxnDateTest()
        {
            // TODO unit test for the property 'TxnDate'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'ValueDate'
        /// </summary>
        [Fact]
        public void ValueDateTest()
        {
            // TODO unit test for the property 'ValueDate'
        }
        /// <summary>
        /// Test the property 'Narration'
        /// </summary>
        [Fact]
        public void NarrationTest()
        {
            // TODO unit test for the property 'Narration'
        }
        /// <summary>
        /// Test the property 'StatementDate'
        /// </summary>
        [Fact]
        public void StatementDateTest()
        {
            // TODO unit test for the property 'StatementDate'
        }
        /// <summary>
        /// Test the property 'Mcc'
        /// </summary>
        [Fact]
        public void MccTest()
        {
            // TODO unit test for the property 'Mcc'
        }
        /// <summary>
        /// Test the property 'MaskedCardNumber'
        /// </summary>
        [Fact]
        public void MaskedCardNumberTest()
        {
            // TODO unit test for the property 'MaskedCardNumber'
        }

    }

}
