/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Api;
using MyDataMyConsent.Models;
using MyDataMyConsent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Test.Model
{
    /// <summary>
    ///  Class for testing DataProviderDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataProviderDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataProviderDetails
        //private DataProviderDetails instance;

        public DataProviderDetailsTests()
        {
            // TODO uncomment below to create an instance of DataProviderDetails
            //instance = new DataProviderDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataProviderDetails
        /// </summary>
        [Fact]
        public void DataProviderDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataProviderDetails
            //Assert.IsType<DataProviderDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'SupportEmail'
        /// </summary>
        [Fact]
        public void SupportEmailTest()
        {
            // TODO unit test for the property 'SupportEmail'
        }
        /// <summary>
        /// Test the property 'HelpLineNumber'
        /// </summary>
        [Fact]
        public void HelpLineNumberTest()
        {
            // TODO unit test for the property 'HelpLineNumber'
        }
        /// <summary>
        /// Test the property 'PrivacyPolicy'
        /// </summary>
        [Fact]
        public void PrivacyPolicyTest()
        {
            // TODO unit test for the property 'PrivacyPolicy'
        }
        /// <summary>
        /// Test the property 'TermOfService'
        /// </summary>
        [Fact]
        public void TermOfServiceTest()
        {
            // TODO unit test for the property 'TermOfService'
        }
        /// <summary>
        /// Test the property 'DataProtectionOfficer'
        /// </summary>
        [Fact]
        public void DataProtectionOfficerTest()
        {
            // TODO unit test for the property 'DataProtectionOfficer'
        }
        /// <summary>
        /// Test the property 'SupportedDocumentTypes'
        /// </summary>
        [Fact]
        public void SupportedDocumentTypesTest()
        {
            // TODO unit test for the property 'SupportedDocumentTypes'
        }
        /// <summary>
        /// Test the property 'SupportedAccountTypes'
        /// </summary>
        [Fact]
        public void SupportedAccountTypesTest()
        {
            // TODO unit test for the property 'SupportedAccountTypes'
        }

    }

}
