/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Api;
using MyDataMyConsent.Models;
using MyDataMyConsent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Test.Model
{
    /// <summary>
    ///  Class for testing FinancialAccountCommercialPaperTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FinancialAccountCommercialPaperTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FinancialAccountCommercialPaperTransaction
        //private FinancialAccountCommercialPaperTransaction instance;

        public FinancialAccountCommercialPaperTransactionTests()
        {
            // TODO uncomment below to create an instance of FinancialAccountCommercialPaperTransaction
            //instance = new FinancialAccountCommercialPaperTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FinancialAccountCommercialPaperTransaction
        /// </summary>
        [Fact]
        public void FinancialAccountCommercialPaperTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" FinancialAccountCommercialPaperTransaction
            //Assert.IsType<FinancialAccountCommercialPaperTransaction>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
