/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyDataMyConsent.Api;
using MyDataMyConsent.Models;
using MyDataMyConsent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyDataMyConsent.Test.Model
{
    /// <summary>
    ///  Class for testing IssuedDocumentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssuedDocumentDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssuedDocumentDetails
        //private IssuedDocumentDetails instance;

        public IssuedDocumentDetailsTests()
        {
            // TODO uncomment below to create an instance of IssuedDocumentDetails
            //instance = new IssuedDocumentDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssuedDocumentDetails
        /// </summary>
        [Fact]
        public void IssuedDocumentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssuedDocumentDetails
            //Assert.IsType<IssuedDocumentDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }
        /// <summary>
        /// Test the property 'IssuedTo'
        /// </summary>
        [Fact]
        public void IssuedToTest()
        {
            // TODO unit test for the property 'IssuedTo'
        }
        /// <summary>
        /// Test the property 'IssuedAtUtc'
        /// </summary>
        [Fact]
        public void IssuedAtUtcTest()
        {
            // TODO unit test for the property 'IssuedAtUtc'
        }
        /// <summary>
        /// Test the property 'ExpiresAtUtc'
        /// </summary>
        [Fact]
        public void ExpiresAtUtcTest()
        {
            // TODO unit test for the property 'ExpiresAtUtc'
        }
        /// <summary>
        /// Test the property 'AcceptedAtUtc'
        /// </summary>
        [Fact]
        public void AcceptedAtUtcTest()
        {
            // TODO unit test for the property 'AcceptedAtUtc'
        }
        /// <summary>
        /// Test the property 'Receiver'
        /// </summary>
        [Fact]
        public void ReceiverTest()
        {
            // TODO unit test for the property 'Receiver'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'DigitalSignatures'
        /// </summary>
        [Fact]
        public void DigitalSignaturesTest()
        {
            // TODO unit test for the property 'DigitalSignatures'
        }

    }

}
