/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.mydatamyconsent.Api;
using com.mydatamyconsent.Model;
using com.mydatamyconsent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.mydatamyconsent.Test.Model
{
    /// <summary>
    ///  Class for testing OrganizationKyoDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganizationKyoDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganizationKyoDocument
        //private OrganizationKyoDocument instance;

        public OrganizationKyoDocumentTests()
        {
            // TODO uncomment below to create an instance of OrganizationKyoDocument
            //instance = new OrganizationKyoDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationKyoDocument
        /// </summary>
        [Fact]
        public void OrganizationKyoDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganizationKyoDocument
            //Assert.IsType<OrganizationKyoDocument>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'DocumentName'
        /// </summary>
        [Fact]
        public void DocumentNameTest()
        {
            // TODO unit test for the property 'DocumentName'
        }
        /// <summary>
        /// Test the property 'StorageUrl'
        /// </summary>
        [Fact]
        public void StorageUrlTest()
        {
            // TODO unit test for the property 'StorageUrl'
        }
        /// <summary>
        /// Test the property 'UploadedAtUtc'
        /// </summary>
        [Fact]
        public void UploadedAtUtcTest()
        {
            // TODO unit test for the property 'UploadedAtUtc'
        }
        /// <summary>
        /// Test the property 'VerifiedBy'
        /// </summary>
        [Fact]
        public void VerifiedByTest()
        {
            // TODO unit test for the property 'VerifiedBy'
        }
        /// <summary>
        /// Test the property 'VerifiedAtUtc'
        /// </summary>
        [Fact]
        public void VerifiedAtUtcTest()
        {
            // TODO unit test for the property 'VerifiedAtUtc'
        }
        /// <summary>
        /// Test the property 'DeletedBy'
        /// </summary>
        [Fact]
        public void DeletedByTest()
        {
            // TODO unit test for the property 'DeletedBy'
        }
        /// <summary>
        /// Test the property 'DeletedAtUtc'
        /// </summary>
        [Fact]
        public void DeletedAtUtcTest()
        {
            // TODO unit test for the property 'DeletedAtUtc'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Fact]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'VerifiedByUser'
        /// </summary>
        [Fact]
        public void VerifiedByUserTest()
        {
            // TODO unit test for the property 'VerifiedByUser'
        }
        /// <summary>
        /// Test the property 'DeletedByUser'
        /// </summary>
        [Fact]
        public void DeletedByUserTest()
        {
            // TODO unit test for the property 'DeletedByUser'
        }
        /// <summary>
        /// Test the property 'Rejection'
        /// </summary>
        [Fact]
        public void RejectionTest()
        {
            // TODO unit test for the property 'Rejection'
        }

    }

}
