/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = MyDataMyConsent.Sdk.Client.OpenAPIDateConverter;

namespace MyDataMyConsent.Sdk.Models
{
    /// <summary>
    /// Defines DocumentCategoryType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DocumentCategoryType
    {
        /// <summary>
        /// Enum Personal for value: Personal
        /// </summary>
        [EnumMember(Value = "Personal")]
        Personal = 1,

        /// <summary>
        /// Enum Education for value: Education
        /// </summary>
        [EnumMember(Value = "Education")]
        Education = 2,

        /// <summary>
        /// Enum Health for value: Health
        /// </summary>
        [EnumMember(Value = "Health")]
        Health = 3,

        /// <summary>
        /// Enum Finance for value: Finance
        /// </summary>
        [EnumMember(Value = "Finance")]
        Finance = 4,

        /// <summary>
        /// Enum Certificates for value: Certificates
        /// </summary>
        [EnumMember(Value = "Certificates")]
        Certificates = 5

    }

}
