/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = MyDataMyConsent.Sdk.Client.OpenAPIDateConverter;

namespace MyDataMyConsent.Sdk.Models
{
    /// <summary>
    /// SupportedIdentifiersByCountry
    /// </summary>
    [DataContract(Name = "SupportedIdentifiersByCountry")]
    public partial class SupportedIdentifiersByCountry : IEquatable<SupportedIdentifiersByCountry>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedIdentifiersByCountry" /> class.
        /// </summary>
        /// <param name="iso2">iso2.</param>
        /// <param name="name">name.</param>
        /// <param name="flag">flag.</param>
        /// <param name="individualIdentifiers">individualIdentifiers.</param>
        /// <param name="organizationIdentifiers">organizationIdentifiers.</param>
        public SupportedIdentifiersByCountry(string? iso2 = default(string?), string? name = default(string?), string? flag = default(string?), List<SupportedIdentifier> individualIdentifiers = default(List<SupportedIdentifier>), List<SupportedIdentifier> organizationIdentifiers = default(List<SupportedIdentifier>))
        {
            this.Iso2 = iso2;
            this.Name = name;
            this.Flag = flag;
            this.IndividualIdentifiers = individualIdentifiers;
            this.OrganizationIdentifiers = organizationIdentifiers;
        }

        /// <summary>
        /// Gets or Sets Iso2
        /// </summary>
        [DataMember(Name = "iso2", EmitDefaultValue = true)]
        public string? Iso2 { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or Sets Flag
        /// </summary>
        [DataMember(Name = "flag", EmitDefaultValue = true)]
        public string? Flag { get; set; }

        /// <summary>
        /// Gets or Sets IndividualIdentifiers
        /// </summary>
        [DataMember(Name = "individualIdentifiers", EmitDefaultValue = true)]
        public List<SupportedIdentifier> IndividualIdentifiers { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationIdentifiers
        /// </summary>
        [DataMember(Name = "organizationIdentifiers", EmitDefaultValue = true)]
        public List<SupportedIdentifier> OrganizationIdentifiers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupportedIdentifiersByCountry {\n");
            sb.Append("  Iso2: ").Append(Iso2).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Flag: ").Append(Flag).Append("\n");
            sb.Append("  IndividualIdentifiers: ").Append(IndividualIdentifiers).Append("\n");
            sb.Append("  OrganizationIdentifiers: ").Append(OrganizationIdentifiers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SupportedIdentifiersByCountry);
        }

        /// <summary>
        /// Returns true if SupportedIdentifiersByCountry instances are equal
        /// </summary>
        /// <param name="input">Instance of SupportedIdentifiersByCountry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SupportedIdentifiersByCountry input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Iso2 == input.Iso2 ||
                    (this.Iso2 != null &&
                    this.Iso2.Equals(input.Iso2))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Flag == input.Flag ||
                    (this.Flag != null &&
                    this.Flag.Equals(input.Flag))
                ) && 
                (
                    this.IndividualIdentifiers == input.IndividualIdentifiers ||
                    this.IndividualIdentifiers != null &&
                    input.IndividualIdentifiers != null &&
                    this.IndividualIdentifiers.SequenceEqual(input.IndividualIdentifiers)
                ) && 
                (
                    this.OrganizationIdentifiers == input.OrganizationIdentifiers ||
                    this.OrganizationIdentifiers != null &&
                    input.OrganizationIdentifiers != null &&
                    this.OrganizationIdentifiers.SequenceEqual(input.OrganizationIdentifiers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Iso2 != null)
                {
                    hashCode = (hashCode * 59) + this.Iso2.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Flag != null)
                {
                    hashCode = (hashCode * 59) + this.Flag.GetHashCode();
                }
                if (this.IndividualIdentifiers != null)
                {
                    hashCode = (hashCode * 59) + this.IndividualIdentifiers.GetHashCode();
                }
                if (this.OrganizationIdentifiers != null)
                {
                    hashCode = (hashCode * 59) + this.OrganizationIdentifiers.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
