name: Generate SDK

on: 
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '14'

            - name: Set up Dotnet 6
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: '6.0.x'
                source-url: https://nuget.pkg.github.com/mydatamyconsent/index.json
              env:
                NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: '15'
                  distribution: 'adopt'

            - name: Install OpenAPI Tools
              run: |
                  npm install @openapitools/openapi-generator-cli -g

            - name: Cleanup folders
              run: |
                rm -rf ./src
                rm -rf ./docs

            - name: Download OpenAPI Spec
              run: curl https://api.mydatamyconsent.com/openapi-spec.json --output openapi-spec.json

            - name: Cleanup Spec
              run: |
                sed -i 's/FinancialAccount\[\(.*\)]/FinancialAccount\1/' openapi-spec.json
                sed -i 's/FinancialAccountTransaction\[\(.*\)]/FinancialAccount\1/' openapi-spec.json
                sed -i 's/PaginatedList<\(.*\)>/PaginatedListOf\1s/' openapi-spec.json

            - name: Generate SDK's
              run: |
                  npx @openapitools/openapi-generator-cli generate

            - run: dotnet build src/MyDataMyConsent/MyDataMyConsent.csproj
            
            - name: Create the package
              run: dotnet pack --configuration Release src/MyDataMyConsent/MyDataMyConsent.csproj

            - uses: actions/delete-package-versions@v3
              with:
                package-name: 'MyDataMyConsent'
                num-old-versions-to-delete: 1
            
            - name: Publish the package to Github Package Registry
              run: dotnet nuget push src/MyDataMyConsent/bin/Release/*.nupkg

#            - name: Publish the package to nuget.org
#              run: dotnet nuget push src/MyDataMyConsent/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
#              env:
#                  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

            - name: Repository update
              uses: EndBug/add-and-commit@v9
              with:
                  author_name: Balamurali Pandranki
                  author_email: balamurali@live.com
                  message: 'Regenerate API SDK'
                  push: true